#include "pch.h"
#include "res_tp_frames.h"

// this file is generated by tool: plist2blist

xx::Task<> ResTpFrames::AsyncLoad(std::string picRoot) {
	{
		auto& eg = xx::EngineBase3::Instance();
#ifdef __EMSCRIPTEN__
		auto tp = co_await eg.AsyncLoadTexturePackerFromUrl<true>(picRoot + "pics.blist");
#else
		auto tp = eg.LoadTexturePacker<true>(picRoot + "pics.blist");
#endif
		xx_assert(tp);
		auto map = tp->GetMapSV();

		this->bullet = map["bullet"sv];
		this->explosion_1 = map["explosion_1"sv];
		this->explosion_2 = map["explosion_2"sv];
		this->explosion_3 = map["explosion_3"sv];
		this->explosion_4 = map["explosion_4"sv];
		this->explosion_5 = map["explosion_5"sv];
		this->monster_1 = map["monster_1"sv];
		this->monster_2 = map["monster_2"sv];
		this->monster_3 = map["monster_3"sv];
		this->monster_4 = map["monster_4"sv];
		this->monster_5 = map["monster_5"sv];
		this->monster_6 = map["monster_6"sv];
		this->number_outlined_0 = map["number_outlined_0"sv];
		this->number_outlined_1 = map["number_outlined_1"sv];
		this->number_outlined_2 = map["number_outlined_2"sv];
		this->number_outlined_3 = map["number_outlined_3"sv];
		this->number_outlined_4 = map["number_outlined_4"sv];
		this->number_outlined_5 = map["number_outlined_5"sv];
		this->number_outlined_6 = map["number_outlined_6"sv];
		this->number_outlined_7 = map["number_outlined_7"sv];
		this->number_outlined_8 = map["number_outlined_8"sv];
		this->number_outlined_9 = map["number_outlined_9"sv];
		this->plane = map["plane"sv];
		this->tile_1 = map["tile_1"sv];
		this->tile_2 = map["tile_2"sv];
		this->tree = map["tree"sv];
	}

	// fill groups

	explosion_.Add(explosion_1);
	explosion_.Add(explosion_2);
	explosion_.Add(explosion_3);
	explosion_.Add(explosion_4);
	explosion_.Add(explosion_5);
	monster_.Add(monster_1);
	monster_.Add(monster_2);
	monster_.Add(monster_3);
	monster_.Add(monster_4);
	monster_.Add(monster_5);
	monster_.Add(monster_6);
	number_outlined_.Add(number_outlined_0);
	number_outlined_.Add(number_outlined_1);
	number_outlined_.Add(number_outlined_2);
	number_outlined_.Add(number_outlined_3);
	number_outlined_.Add(number_outlined_4);
	number_outlined_.Add(number_outlined_5);
	number_outlined_.Add(number_outlined_6);
	number_outlined_.Add(number_outlined_7);
	number_outlined_.Add(number_outlined_8);
	number_outlined_.Add(number_outlined_9);
	tile_.Add(tile_1);
	tile_.Add(tile_2);
	co_return;
}
