#pragma once
#include "pch.h"

// this file is generated by tool: plist2blist

struct ResTpFrames {
	xx::Task<> AsyncLoad(std::string picRoot);

	xx::Ref<xx::Frame> bullet;
	xx::Ref<xx::Frame> explosion_1;
	xx::Ref<xx::Frame> explosion_2;
	xx::Ref<xx::Frame> explosion_3;
	xx::Ref<xx::Frame> explosion_4;
	xx::Ref<xx::Frame> explosion_5;
	xx::Ref<xx::Frame> monster_1;
	xx::Ref<xx::Frame> monster_2;
	xx::Ref<xx::Frame> monster_3;
	xx::Ref<xx::Frame> monster_4;
	xx::Ref<xx::Frame> monster_5;
	xx::Ref<xx::Frame> monster_6;
	xx::Ref<xx::Frame> number_outlined_0;
	xx::Ref<xx::Frame> number_outlined_1;
	xx::Ref<xx::Frame> number_outlined_2;
	xx::Ref<xx::Frame> number_outlined_3;
	xx::Ref<xx::Frame> number_outlined_4;
	xx::Ref<xx::Frame> number_outlined_5;
	xx::Ref<xx::Frame> number_outlined_6;
	xx::Ref<xx::Frame> number_outlined_7;
	xx::Ref<xx::Frame> number_outlined_8;
	xx::Ref<xx::Frame> number_outlined_9;
	xx::Ref<xx::Frame> plane;
	xx::Ref<xx::Frame> tile_1;
	xx::Ref<xx::Frame> tile_2;
	xx::Ref<xx::Frame> tree;

	xx::Listi32<xx::Ref<xx::Frame>> explosion_;
	xx::Listi32<xx::Ref<xx::Frame>> monster_;
	xx::Listi32<xx::Ref<xx::Frame>> number_outlined_;
	xx::Listi32<xx::Ref<xx::Frame>> tile_;
};
