#include "pch.h"

// this file is generated by tool: pics2loadcode

struct ResFrames {
	xx::Task<> AsyncLoad(std::vector<std::pair<std::string, xx::Ref<xx::Frame>*>>& ffs, std::string picRoot, int32_t texSiz = 1024);
	xx::Task<> AsyncLoad(std::string picRoot, int32_t texSiz = 1024);


	xx::Ref<xx::Frame> blade_light;
	xx::Ref<xx::Frame> button;
	xx::Ref<xx::Frame> circle;
	xx::Ref<xx::Frame> cring;
	xx::Ref<xx::Frame> explosion_13_1;
	xx::Ref<xx::Frame> explosion_13_2;
	xx::Ref<xx::Frame> explosion_13_3;
	xx::Ref<xx::Frame> explosion_13_4;
	xx::Ref<xx::Frame> explosion_13_5;
	xx::Ref<xx::Frame> explosion_13_6;
	xx::Ref<xx::Frame> explosion_13_7;
	xx::Ref<xx::Frame> ring;
	xx::Ref<xx::Frame> quad;

	xx::Listi32<xx::Ref<xx::Frame>> explosion_13_;
	static constexpr int32_t frame_count_explosion_13_{ 7 };
};
